version: "3"
services:
  apache:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./clases:/var/www/html
      - ./apache/logs:/var/log/apache2