version: "3"
services:
  apache:
    build: apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/logs:/var/log/apache2
    depends_on:
      - "mysql"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PORT: 3306
    volumes:
      - ./db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
    depends_on:
      - "mysql"
    ports:
      - "8081:80"